
package calculadoramatrices;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;



public class CalculadoraMatrices extends javax.swing.JFrame {
    //Declaración variables globales.
    private int na, ma, nb, mb;
    private int a[][],b[][];
    
    //Constructores normales
    IInterface mat = new Matriz1();
    IInterface sum = new Sumar();
    IInterface res = new Restar();
    IInterface traz = new Traza(); 
    IInterface det = new Determinante();
    
    

    /**
     * Creates new form NewJFrame
     */
    public CalculadoraMatrices() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        botSumar = new javax.swing.JButton();
        botRestar = new javax.swing.JButton();
        botTrazaA = new javax.swing.JButton();
        botDeterA = new javax.swing.JButton();
        botBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filasA = new javax.swing.JTextField();
        columnasA = new javax.swing.JTextField();
        filasB = new javax.swing.JTextField();
        columnasB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMatriz1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMatriz2 = new javax.swing.JTextArea();
        botTrazaB = new javax.swing.JButton();
        botDeterB = new javax.swing.JButton();

        jScrollPane3.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 51));

        botSumar.setBackground(new java.awt.Color(14, 100, 121));
        botSumar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botSumar.setForeground(new java.awt.Color(255, 255, 255));
        botSumar.setText("SUMAR");
        botSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSumarActionPerformed(evt);
            }
        });

        botRestar.setBackground(new java.awt.Color(14, 100, 121));
        botRestar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botRestar.setForeground(new java.awt.Color(255, 255, 255));
        botRestar.setText("RESTAR");
        botRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRestarActionPerformed(evt);
            }
        });

        botTrazaA.setBackground(new java.awt.Color(14, 100, 121));
        botTrazaA.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botTrazaA.setForeground(new java.awt.Color(255, 255, 255));
        botTrazaA.setText("TRAZA MATRIZ A");
        botTrazaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTrazaAActionPerformed(evt);
            }
        });

        botDeterA.setBackground(new java.awt.Color(14, 100, 121));
        botDeterA.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botDeterA.setForeground(new java.awt.Color(255, 255, 255));
        botDeterA.setText("DETERMINANTE MATRIZ A");
        botDeterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDeterAActionPerformed(evt);
            }
        });

        botBorrar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botBorrar.setForeground(new java.awt.Color(255, 51, 102));
        botBorrar.setText("BORRAR");
        botBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA DE MATRICES");

        jLabel2.setText("MATRIZ A");

        jLabel3.setText("MATRIZ B");

        jLabel4.setText("Filas:");

        jLabel5.setText("Columnas:");

        jLabel6.setText("TAMAÑO MATRIZ B");

        jLabel7.setText("TAMAÑO MATRIZ A");

        jLabel8.setText("Filas:");

        jLabel9.setText("Columnas:");

        filasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasAActionPerformed(evt);
            }
        });

        columnasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasAActionPerformed(evt);
            }
        });

        filasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasBActionPerformed(evt);
            }
        });

        columnasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasBActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(11, 108, 127));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GENERAR MATRIZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtMatriz1.setColumns(20);
        txtMatriz1.setRows(5);
        jScrollPane1.setViewportView(txtMatriz1);

        txtMatriz2.setColumns(20);
        txtMatriz2.setRows(5);
        jScrollPane2.setViewportView(txtMatriz2);

        botTrazaB.setBackground(new java.awt.Color(14, 100, 121));
        botTrazaB.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botTrazaB.setForeground(new java.awt.Color(255, 255, 255));
        botTrazaB.setText("TRAZA MATRIZ B");
        botTrazaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTrazaBActionPerformed(evt);
            }
        });

        botDeterB.setBackground(new java.awt.Color(14, 100, 121));
        botDeterB.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botDeterB.setForeground(new java.awt.Color(255, 255, 255));
        botDeterB.setText("DETERMINANTE MATRIZ B");
        botDeterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDeterBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botSumar)
                                .addGap(18, 18, 18)
                                .addComponent(botDeterA)
                                .addGap(18, 18, 18)
                                .addComponent(botTrazaA))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botBorrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botRestar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botDeterB)))
                                .addGap(18, 18, 18)
                                .addComponent(botTrazaB))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(columnasA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filasA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filasB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(columnasB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(filasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(columnasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(filasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(columnasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botSumar)
                    .addComponent(botDeterA)
                    .addComponent(botTrazaA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botRestar)
                    .addComponent(botDeterB)
                    .addComponent(botTrazaB))
                .addGap(18, 18, 18)
                .addComponent(botBorrar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Acción botón sumar: suma matriz A con matriz B.
    private void botSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSumarActionPerformed
        //Valida si matriz A y matriz B son compatibles para suma.
        if (na==nb && ma==mb) {
            int c[][]=sum.suma(a,b, na, ma);
            //Imprime matriz en pantalla
            JOptionPane.showMessageDialog(null, mat.imprimir(c, na, ma));
            
        } else {
            JOptionPane.showMessageDialog(null, "La matriz no es compatible");
        }
        
       

    }//GEN-LAST:event_botSumarActionPerformed
    //Procedimiento para imprimir la matriz A en el cuadro de txtMatriz1 sin borrar valores ya impresos, con ayuda de .append().
    private void imprimirMatriz1(int[][] b, int fil,int col) {
        
       
        for (int i = 0; i < fil; i++) {
            String a="";
            for (int j = 0; j < col; j++) {
                a+=b[i][j]+" ";                              
            }
            txtMatriz1.append(a+"\n");
        }
        
    }
    //Procedimiento para imprimir la matriz B en el cuadro de txtMatriz2 sin borrar valores ya impresos, con ayuda de .append().
    private void imprimirMatriz2(int[][] b, int fil,int col) {
        
        
        for (int i = 0; i < fil; i++) {
            String a="";
            for (int j = 0; j < col; j++) {
                a+=b[i][j]+" ";                              
            }
            txtMatriz2.append(a+"\n");
        }
        
    }
    //Acción botón restar: resta matriz A con matriz B.
    private void botRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRestarActionPerformed
        //Valida si matriz A y matriz B son compatibles para resta.
        if (na==nb && ma==mb) {
            
            
            int c[][]=res.resta(a,b, na, ma);
            JOptionPane.showMessageDialog(null, mat.imprimir(c, na, ma));
            
        } else {
            JOptionPane.showMessageDialog(null, "La matriz no es compatible");
        } 
    }//GEN-LAST:event_botRestarActionPerformed
    //Procedimiento para dejar casillas que reciben texto en blanco y recibir una nueva matriz
    private void botBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBorrarActionPerformed
        filasA.setText("");
        filasB.setText("");
        columnasA.setText("");
        columnasB.setText("");
        txtMatriz1.setText("");
        txtMatriz2.setText("");
        
    }//GEN-LAST:event_botBorrarActionPerformed
    //Procedimiento para captar el valor de la casilla filasA para recibir número de filas matriz A
    private void filasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasAActionPerformed
        na = Integer.parseInt(filasA.getText());
    }//GEN-LAST:event_filasAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        na = Integer.parseInt(filasA.getText());
        ma = Integer.parseInt(columnasA.getText());
        nb = Integer.parseInt(filasB.getText());
        mb = Integer.parseInt(columnasB.getText());
        a=mat.matriz(na, ma);
        b=mat.matriz(nb, mb);
        imprimirMatriz1(a, na, ma);
        imprimirMatriz2(b, nb, mb);
    }//GEN-LAST:event_jButton1ActionPerformed
    //Procedimiento para captar el valor de la casilla columnasA para recibir número de columnas matriz A.
    private void columnasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasAActionPerformed
      ma = Integer.parseInt(columnasA.getText());
    }//GEN-LAST:event_columnasAActionPerformed
    //Procedimiento para captar el valor de la casilla filasB para recibir número de filas matriz B.
    private void filasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasBActionPerformed
        nb=Integer.parseInt(filasB.getText());
    }//GEN-LAST:event_filasBActionPerformed
    //Procedimiento para captar el valor de la casilla columnasB para recibir número de filas matriz B.
    private void columnasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasBActionPerformed
        mb=Integer.parseInt(columnasB.getText());
    }//GEN-LAST:event_columnasBActionPerformed
    //Acción botón Traza Matriz A: calcula la diagonal principal de la matriz y suma valores de la misma.
    private void botTrazaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTrazaAActionPerformed

        if (na==ma) {
            
            int c=traz.traza(a, na, ma);
            JOptionPane.showMessageDialog(null, "La traza de la matriz A es: \n"+c);
            
        } else {
            JOptionPane.showMessageDialog(null, "La matriz no es cuadrada, por favor ingresar misma cantidad de filas y columnas");
        }  
    }//GEN-LAST:event_botTrazaAActionPerformed
       //Acción botón Traza Matriz B: calcula la diagonal principal de la matriz y suma valores de la misma
    private void botTrazaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTrazaBActionPerformed
        if (nb==mb) {
            
            int c=traz.traza(b, nb, mb);
            JOptionPane.showMessageDialog(null, "La traza de la matriz B es: \n"+c);
            
        } else {
            JOptionPane.showMessageDialog(null, "La matriz no es cuadrada, por favor ingresar misma cantidad de filas y columnas");
        }  
    }//GEN-LAST:event_botTrazaBActionPerformed
    //Acción botón Determinante Matriz A: calcula determinante de la matriz A.
    private void botDeterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDeterAActionPerformed
        if (na==ma) {
            
            int c=det.determinanteMatriz(a, na);
            JOptionPane.showMessageDialog(null, "La determinante de la matriz A es: \n"+c);
            
        }else{
            JOptionPane.showMessageDialog(null, "La matriz no es cuadrada");
        }
    }//GEN-LAST:event_botDeterAActionPerformed
    //Acción botón Determinante Matriz B: calcula determinante de la matriz B.
    private void botDeterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDeterBActionPerformed
        if (nb==mb) {
            
            int c=det.determinanteMatriz(b, nb);
            JOptionPane.showMessageDialog(null, "La determinante de la matriz B es: \n"+c);
            
        }else{
            JOptionPane.showMessageDialog(null, "La matriz no es cuadrada");
        }
    }//GEN-LAST:event_botDeterBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CalculadoraMatrices().setVisible(true);
            }
        });
    }
    
    public CalculadoraMatrices(int na, int ma, int nb, int mb, JButton botBorrar, JButton botDeter, JButton botRestar, JButton botSumar, JButton botTraza, JTextField columnasA, JTextField columnasB, JTextField filasA, JTextField filasB, JButton jButton1, JLabel jLabel1, JLabel jLabel2, JLabel jLabel3, JLabel jLabel4, JLabel jLabel5, JLabel jLabel6, JLabel jLabel7, JLabel jLabel8, JLabel jLabel9, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JTextArea txtMatriz1, JTextArea txtMatriz2) {
        this.na = na;
        this.ma = ma;
        this.nb = nb;
        this.mb = mb;
        this.botBorrar = botBorrar;
        this.botDeterA = botDeter;
        this.botRestar = botRestar;
        this.botSumar = botSumar;
        this.botTrazaA = botTraza;
        this.columnasA = columnasA;
        this.columnasB = columnasB;
        this.filasA = filasA;
        this.filasB = filasB;
        this.jButton1 = jButton1;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jLabel6 = jLabel6;
        this.jLabel7 = jLabel7;
        this.jLabel8 = jLabel8;
        this.jLabel9 = jLabel9;
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.txtMatriz1 = txtMatriz1;
        this.txtMatriz2 = txtMatriz2;
    }

    
    
   //Getters
    public JTextField getColumnasA() {
        return columnasA;
    }

    public JTextField getColumnasB() {
        return columnasB;
    }

    public JTextField getFilasA() {
        return filasA;
    }

    public JTextField getFilasB() {
        return filasB;
    }
    
   
            

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botBorrar;
    private javax.swing.JButton botDeterA;
    private javax.swing.JButton botDeterB;
    private javax.swing.JButton botRestar;
    private javax.swing.JButton botSumar;
    private javax.swing.JButton botTrazaA;
    private javax.swing.JButton botTrazaB;
    private javax.swing.JTextField columnasA;
    private javax.swing.JTextField columnasB;
    private javax.swing.JTextField filasA;
    private javax.swing.JTextField filasB;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtMatriz1;
    private javax.swing.JTextArea txtMatriz2;
    // End of variables declaration//GEN-END:variables
}
